# Get all lectures
GET http://localhost:5000/lectures

###

# Get lecture by id
GET http://localhost:5000/lectures/601c8218e8f67c076c760880

###

# Create lecture (module id)

POST http://localhost:5000/lectures/6019a788f04efb4794dc2312
Content-Type: application/json

{
  "title": "Nombre Lecture",
  "imagen": "Imagen Lecture",
  "description": "Descripcion Lecture",
  "moduloName": "Modulo 3",
  "urlLecture": "URL Lecture"
}

###

# Update lecture (id)
PATCH http://localhost:5000/lectures/601c8218e8f67c076c760880
Content-Type: application/json

{
  "title": "Title Lecture"
}

###

# Delete one lecture (id)
DELETE http://localhost:5000/lectures/601c8218e8f67c076c760880

###
