# Get all modules

GET http://localhost:5000/modules/

###

# Get one module

GET http://localhost:5000/modules/6019a788f04efb4794dc2312

###

# Create one module

POST http://localhost:5000/modules/
Content-Type: application/json

{
  "title": "Modulo 1",
  "lectures": "8",
  "description": "Javascript avanzado"
}

###

# Update one module

PATCH http://localhost:5000/modules/6019a788f04efb4794dc2312
Content-Type: application/json

{
  "title": "Modulo 3",
  "description": "Javascript avanzado",
  "lectures": []
}

###
